version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
      - "5672:5672"
      
  consumer:
    build: ./consumer
    depends_on:
      - rabbitmq
    restart: on-failure
    volumes:
      - ./data:/app/data
      
  producer:
    build: ./producer
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq

